import os
import json
from dotenv import load_dotenv
from langsmith import Client

backend_env = os.path.join(os.path.dirname(__file__), "..", "deepagent", ".env")
load_dotenv(backend_env)
load_dotenv(override=True)

# Some environments use LANGCHAIN_API_KEY, some use LANGSMITH_API_KEY
if "LANGSMITH_API_KEY" in os.environ and "LANGCHAIN_API_KEY" not in os.environ:
    os.environ["LANGCHAIN_API_KEY"] = os.environ["LANGSMITH_API_KEY"]

# Initialize LangSmith client
client = Client()

PROJECT_NAME = os.getenv("LANGSMITH_PROJECT", os.getenv("LANGCHAIN_PROJECT", "homebot-deepagent"))

def fetch_top_traces(run_id=None, limit=100):
    """
    Fetch traces from the deepagent project that have positive feedback
    or were automatically generated by our distillation simulator.
    """
    print(f"Fetching distilled traces from project: {PROJECT_NAME}")
    if run_id:
        print(f"Filtering purely by Run ID: {run_id}")
    
    all_runs = client.list_runs(
        project_name=PROJECT_NAME,
        run_type="chain",
        limit=100  # API max is 100
    )
    
    runs_list = list(all_runs)
    extracted_data = []
    
    for run in runs_list:
        if len(extracted_data) >= limit:
            break
            
        if not run.inputs or not run.outputs:
            continue
            
        # Check either tags or our distinct thread_id
        tags = run.tags or []
        metadata = run.extra.get("metadata", {}) if run.extra else {}
        thread_id = metadata.get("thread_id", "")
        
        if run_id:
            is_distillation = run_id in tags
        else:
            is_distillation = "distillation_simulation" in tags or "distill_sim_" in str(thread_id)
        
        if is_distillation:
            extracted_data.append({
                "id": str(run.id),
                "inputs": run.inputs,
                "outputs": run.outputs,
            })
        
    print(f"✅ Extracted {len(extracted_data)} runs from LangSmith.")
    return extracted_data

def export_to_jsonl(data, filename="data/langsmith_export.jsonl"):
    """Export the list of runs to JSONL format."""
    
    # Ensure data folder exists
    os.makedirs(os.path.dirname(os.path.abspath(filename)), exist_ok=True)
    
    with open(filename, "w") as f:
        for item in data:
            f.write(json.dumps(item) + "\n")
    print(f"✅ Exported to {filename}")

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="LangSmith Extractor")
    parser.add_argument("--run-id", type=str, default=None, help="Filter specifically by run ID tag")
    args = parser.parse_args()
    
    runs = fetch_top_traces(run_id=args.run_id)
    if runs:
        export_to_jsonl(runs)
    else:
        print("No usable traces found. Try generating synthetic data first.")
